name: HelloWorld
on: [push]
jobs:

  variables:
      monTexte: "Bonjour le monde"

  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, world!.

  job2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo $montexte
