name: HelloWorld
on: [push]
env:
  maVar: "var"
jobs:

  job1:
    on: push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, world!.

  job2:
    on: pull_request
    runs-on: ubuntu-latest
    env:
      monTexte: "Bonjour le monde"
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo $montexte
